### ISSUE TITLE
Вставлять ответ на begin триггер последним словом

### ISSUE THREAD

**Issue by tynopet** [ustits/ColleagueBot#31]
Если люди пишут begin апчхи кхе писать ответ на begin в конце для большей консистентности. Придется костылить

**Comment by ustits** [comment]
Does it mean that for some triggers there must be an ability to customize print order? 
If you mean this I have a couple of question:
1. How user will specify this? As an extra attribute in `/trigger` command?
2. If the specify print order, how shall we resolve conflicts, when some triggers have the same priority?

**Comment by ustits** [comment]
Closing due to no response
