### ISSUE TITLE
ignore whitespace triggers

### ISSUE THREAD

**Issue by ustits** [ustits/ColleagueBot#35]
Must check cases like: `/trigger   test` (3 spaces)

**Comment by dmchubukov** [comment]
and 2 spaces too

**Comment by ustits** [comment]
Checking whitespaces just in a trigger is not really correct. We also need to verify that repeat commands don't have such problems eigther.
Made a separate command wrapper that replaces all whitespace arguments.
With such solution we eliminate all excess whitespaces also in messages.
Suppose it is not a problem, because it is more important to save safety of significant fields, than try to keep user's original message  
Used in repeat and trigger commands.
